node:
  image: ubuntu:14.04
  volumes:
    - .:/var/app/
  working_dir: "/var/app"
  ports:
   - "3000:3000"
   - "3001:3001"
   - "5000:5000"
  expose:
    - 3000
    - 3001
    - 5000
  command: /bin/bash ./docker/node/init.sh
  external_links:
   - afapi_dev_1:afapi
